services:

  postgres:
    image: postgres:15
    container_name: quarkus-postgres
    environment:
      POSTGRES_USER: topicos1
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: quarkus_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  h2db:
    image: oscarfonts/h2
    container_name: quarkus-h2
    environment:
      H2_OPTIONS: '-tcpAllowOthers'
    ports:
      - "9092:9092"
      - "8082:8082"
    restart: always

  mongodb:
    image: mongo:5.0
    container_name: graylog-mongodb
    networks:
      - graylog-network
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: graylog-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    networks:
      - graylog-network
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data

  graylog:
    image: graylog/graylog:5.1
    container_name: graylog-server
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
      - GRAYLOG_ROOT_PASSWORD_SHA2=e9b0d3776db19e2b5d416a52f62bd8c864586491db434a333244abbb1a0f1e76
      - GRAYLOG_PASSWORD_SECRET=SOhOPHf16XnyCgK3tHdPK2jnBEyToLXzL3hIuPC/J2U=
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
    depends_on:
      - mongodb
      - elasticsearch
    networks:
      - graylog-network
    ports:
      - "9000:9000"
      - "12201:12201/udp"
    restart: unless-stopped
    volumes:
      - graylog_data:/usr/share/graylog/data

networks:
  graylog-network:

volumes:
  mongo_data:
  es_data:
  graylog_data:
  postgres_data: {}